# Site settings
title: Olapic Public Documentation
email: support@olapic.com
description: "This documentation contains all public documentation."
url: "http://developer.olapic.com"

# Build settings
markdown: kramdown
highlighter: rouge

permalink: none

# Custom settings
category-list: [Javascript Widget, Checkout Code, Product Feed]
