# Site settings
title: Olapic Public Documentation
email: support@olapic.com
description: "This documentation contains all public documentation."
baseurl: "/PublicDocs"
url: "http://olapic.com"

# Build settings
markdown: kramdown
highlighter: rouge

permalink: none

# Custom settings
category-list: [JS Widget, Checkout Code, Product Feed]
