# Site settings
title: Olapic - Developer Resources
email: jae@olapic.com
description: "Developer resources for the Olapic platform."
url: "http://developer.olapic.com"

# Build settings
markdown: kramdown
highlighter: rouge

permalink: none

# Custom settings
category-list: [Javascript Widget, Checkout Code, Product Feed, Exports]
collections: 
  articles: 
    output: true
gems:
  - jekyll-redirect-from