# Site settings
title: Olapic Public Documentation
email: jae@olapic.com
description: "This documentation contains all public documentation."
baseurl: ""
url: "http://olapic.com"

# Build settings
markdown: kramdown
permalink: none

# Custom settings
category-list: [articles, feed, checkout]