# Site settings
title: Olapic Public Documentation
email: support@olapic.com
description: "This documentation contains all public documentation."
baseurl: "/PublicDocs"
url: "http://olapic.com"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "autolink", "tables","with_toc_data"]

permalink: none

# Custom settings
category-list: [Resources]
