# Site settings
title: Olapic Public Documentation
email: support@olapic.com
description: "This documentation contains all public documentation."
baseurl: "/PublicDocs"
url: "http://olapic.com"

# Build settings
markdown: redcarpet
redcarpet: 
  fenced_code_blocks: true

permalink: none

# Custom settings
category-list: [Resources]
