# Site settings
title: Olapic - Developer Resources
email: jae@olapic.com
description: "Developer resources for the Olapic platform."
url: "http://developer.olapic.com"

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: javascript
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

permalink: none

# Custom settings
category-list: [API Resources, 3rd Party Integrations, Javascript Widget, Checkout Code, Product Feed, Exports]
collections: 
  articles: 
    output: true
gems:
  - jekyll-redirect-from
sass:
  style: compact